In [72]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("Bacteria_dataset_Multiresictance.csv")
df.head(10)

,ID,Name,Email,Address,age/gender,Souches,Diabetes,Hypertension,Hospital_before,Infection_Freq,...,AN,Acide nalidixique,ofx,CIP,C,Co-trimoxazole,Furanes,colistine,Collection_Date,Notes
0,S290,Elizabeth Lawrence,elizabeth.lawrence@example.com,"6350 Robinson Loaf Apt. 447, Paulfurt, RI 30252",37/F,S290 Escherichia coli,No,No,No,0.0,...,S,S,S,S,R,S,S,S,5 Fev 2025,Patient had fever??
1,S291,Tina Sanders,tina.sanders@example.com,"78594 Galloway Port Suite 762, South Tanyatown...",29/F,S291 Morganella morganii,True,No,No,3.0,...,S,S,S,S,S,S,S,S,08/05/2021,تم العلاج
2,S292,Erin Cooke,erin.cooke@example.com,"76661 Isaiah Manors, North Benjamin, HI 85195",77/F,S292 Proteus mirabilis,True,No,No,3.0,...,S,S,S,R,R,S,S,S,01/05/2022,NADA
3,S293,Mrs. Sharon Watson,mrs..sharon.watson@example.com,"1670 Thompson Way Apt. 520, Andrewbury, IL 11534",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-05,PACIENTO ENFERMO
4,S294,Erika Stewart,erika.stewart@example.com,"76838 Patrick Green Suite 538, Torresmouth, ME...",13/F,S294 Escherichia coli,No,Yes,No,1.0,...,R,S,S,S,S,S,S,S,error,NADA
5,S295,Krystal Riley,krystal.riley@example.com,"USNS Neal, FPO AA 98816",57/M,S295 Escherichia coli,True,No,No,3.0,...,R,S,S,S,S,S,S,S,2020-01-05,Patient had fever??
6,S296,Gina Griffin,gina.griffin@example.com,"389 Ferguson Island, West Jefferymouth, MT 89882",68/F,S296 Escherichia coli,No,No,No,3.0,...,S,S,S,S,S,S,S,S,2020-12-31,see file
7,S297,Faith Newman,faith.newman@example.com,"256 Bartlett Fork Suite 334, East Sherri, MI 9...",18/F,S297 Citrobacter spp.,No,No,No,2.0,...,S,S,S,S,S,R,S,S,05/03/2022,تم العلاج
8,S298,Russell Hicks,russell.hicks@example.com,"77940 Richard Brook Apt. 748, South Jessica, G...",77/F,S298 Enterobacteria spp.,No,No,No,0.0,...,S,S,S,S,S,S,S,S,05/01/2025,MALADIE GRAVE
9,S299,Kimberly Rodriguez,kimberly.rodriguez@example.com,"1979 Kayla Squares Suite 125, West Cynthia, MO...",36/F,S299 Proeus mirabilis,No,No,No,3.0,...,S,R,S,S,S,S,S,S,08/05/2021,Patient had fever??

In [73]:
df.tail()

,ID,Name,Email,Address,age/gender,Souches,Diabetes,Hypertension,Hospital_before,Infection_Freq,...,AN,Acide nalidixique,ofx,CIP,C,Co-trimoxazole,Furanes,colistine,Collection_Date,Notes
10705,S10995,Mrs. Chelsea Brown MD,mrs..chelsea.brown.md@example.com,"23574 Palmer Lodge, South Aliciaton, GU 00728",17/M,S7382 Enterobacteria spp.,No,No,No,3.0,...,S,S,S,S,S,S,S,S,2024-12-31,see file
10706,S10996,Mary Kelley,mary.kelley@example.com,"8194 Gonzalez Hill, Loveview, SD 31189",20/F,S1479 Proeus mirabilis,True,No,Yes,3.0,...,S,S,S,S,S,S,S,S,5 Fev 2025,Patient had fever??
10707,S10997,Alexandra Smith,alexandra.smith@example.com,"213 Yates Station, Port Meganstad, PW 17799",33/M,S2983 Escherichia coli,No,No,No,0.0,...,S,S,R,S,R,S,S,S,08/05/2021,Patient had fever??
10708,S10998,April Cox,april.cox@example.com,"985 Julia Freeway Apt. 753, Dianamouth, SD 07610",86/F,S10079 Escherichia coli,No,No,No,2.0,...,s,i,r,r,s,Intermediate,r,s,05/03/2022,see file
10709,S10999,Richard Jarvis,richard.jarvis@example.com,"2903 James Motorway Suite 202, Whitakerside, C...",?,NaN,missing,?,NaN,NaN,...,NaN,NaN,missing,NaN,?,?,NaN,?,?,NaN

In [74]:
missing_value=round((df.isnull().sum())/len(df)*100,2)
print(missing_value)

ID                   0.00
Name                 0.00
Email                0.00
Address              0.00
age/gender           5.80
Souches              5.98
Diabetes             5.93
Hypertension         5.88
Hospital_before      5.95
Infection_Freq       5.97
AMX/AMP              6.14
AMC                  5.90
CZ                   5.86
FOX                  5.84
CTX/CRO              5.83
IPM                  5.91
GEN                  6.00
AN                   5.86
Acide nalidixique    5.81
ofx                  5.77
CIP                  5.91
C                    5.87
Co-trimoxazole       5.98
Furanes              5.95
colistine            5.94
Collection_Date      6.25
Notes                1.05
dtype: float64

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10710 entries, 0 to 10709
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 10710 non-null  object
 1   Name               10710 non-null  object
 2   Email              10710 non-null  object
 3   Address            10710 non-null  object
 4   age/gender         10089 non-null  object
 5   Souches            10070 non-null  object
 6   Diabetes           10075 non-null  object
 7   Hypertension       10080 non-null  object
 8   Hospital_before    10073 non-null  object
 9   Infection_Freq     10071 non-null  object
 10  AMX/AMP            10052 non-null  object
 11  AMC                10078 non-null  object
 12  CZ                 10082 non-null  object
 13  FOX                10085 non-null  object
 14  CTX/CRO            10086 non-null  object
 15  IPM                10077 non-null  object
 16  GEN                10067 non-null  object
 17  AN                 10082 non-null  object
 18  Acide nalidixique  10088 non-null  object
 19  ofx                10092 non-null  object
 20  CIP                10077 non-null  object
 21  C                  10081 non-null  object
 22  Co-trimoxazole     10070 non-null  object
 23  Furanes            10073 non-null  object
 24  colistine          10074 non-null  object
 25  Collection_Date    10041 non-null  object
 26  Notes              10598 non-null  object
dtypes: object(27)
memory usage: 2.2+ MB

In [76]:
df.isnull().sum()

ID                     0
Name                   0
Email                  0
Address                0
age/gender           621
Souches              640
Diabetes             635
Hypertension         630
Hospital_before      637
Infection_Freq       639
AMX/AMP              658
AMC                  632
CZ                   628
FOX                  625
CTX/CRO              624
IPM                  633
GEN                  643
AN                   628
Acide nalidixique    622
ofx                  618
CIP                  633
C                    629
Co-trimoxazole       640
Furanes              637
colistine            636
Collection_Date      669
Notes                112
dtype: int64

In [77]:
df.columns

Index(['ID', 'Name', 'Email', 'Address', 'age/gender', 'Souches', 'Diabetes',
       'Hypertension', 'Hospital_before', 'Infection_Freq', 'AMX/AMP', 'AMC',
       'CZ', 'FOX', 'CTX/CRO', 'IPM', 'GEN', 'AN', 'Acide nalidixique', 'ofx',
       'CIP', 'C', 'Co-trimoxazole', 'Furanes', 'colistine', 'Collection_Date',
       'Notes'],
      dtype='object')

In [9]:
df["age/gender"].fillna(df["age/gender"].mode()[0],inplace=True)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_12844\2804683695.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age/gender"].fillna(df["age/gender"].mode()[0],inplace=True)

In [10]:
df["Souches"].fillna(df["Souches"].mode()[0],inplace=True)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_12844\2349065298.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Souches"].fillna(df["Souches"].mode()[0],inplace=True)

In [78]:
df[["Age","Gender"]]=df['age/gender'].str.split('/',expand=True)

In [79]:
df.head(10)

,ID,Name,Email,Address,age/gender,Souches,Diabetes,Hypertension,Hospital_before,Infection_Freq,...,ofx,CIP,C,Co-trimoxazole,Furanes,colistine,Collection_Date,Notes,Age,Gender
0,S290,Elizabeth Lawrence,elizabeth.lawrence@example.com,"6350 Robinson Loaf Apt. 447, Paulfurt, RI 30252",37/F,S290 Escherichia coli,No,No,No,0.0,...,S,S,R,S,S,S,5 Fev 2025,Patient had fever??,37,F
1,S291,Tina Sanders,tina.sanders@example.com,"78594 Galloway Port Suite 762, South Tanyatown...",29/F,S291 Morganella morganii,True,No,No,3.0,...,S,S,S,S,S,S,08/05/2021,تم العلاج,29,F
2,S292,Erin Cooke,erin.cooke@example.com,"76661 Isaiah Manors, North Benjamin, HI 85195",77/F,S292 Proteus mirabilis,True,No,No,3.0,...,S,R,R,S,S,S,01/05/2022,NADA,77,F
3,S293,Mrs. Sharon Watson,mrs..sharon.watson@example.com,"1670 Thompson Way Apt. 520, Andrewbury, IL 11534",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-05,PACIENTO ENFERMO,NaN,NaN
4,S294,Erika Stewart,erika.stewart@example.com,"76838 Patrick Green Suite 538, Torresmouth, ME...",13/F,S294 Escherichia coli,No,Yes,No,1.0,...,S,S,S,S,S,S,error,NADA,13,F
5,S295,Krystal Riley,krystal.riley@example.com,"USNS Neal, FPO AA 98816",57/M,S295 Escherichia coli,True,No,No,3.0,...,S,S,S,S,S,S,2020-01-05,Patient had fever??,57,M
6,S296,Gina Griffin,gina.griffin@example.com,"389 Ferguson Island, West Jefferymouth, MT 89882",68/F,S296 Escherichia coli,No,No,No,3.0,...,S,S,S,S,S,S,2020-12-31,see file,68,F
7,S297,Faith Newman,faith.newman@example.com,"256 Bartlett Fork Suite 334, East Sherri, MI 9...",18/F,S297 Citrobacter spp.,No,No,No,2.0,...,S,S,S,R,S,S,05/03/2022,تم العلاج,18,F
8,S298,Russell Hicks,russell.hicks@example.com,"77940 Richard Brook Apt. 748, South Jessica, G...",77/F,S298 Enterobacteria spp.,No,No,No,0.0,...,S,S,S,S,S,S,05/01/2025,MALADIE GRAVE,77,F
9,S299,Kimberly Rodriguez,kimberly.rodriguez@example.com,"1979 Kayla Squares Suite 125, West Cynthia, MO...",36/F,S299 Proeus mirabilis,No,No,No,3.0,...,S,S,S,S,S,S,08/05/2021,Patient had fever??,36,F

In [92]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [81]:
df["Gender"].isnull().sum()

np.int64(763)

In [93]:
df["Age"].fillna(df["Age"].mean(),inplace=True)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_12844\2595122914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [83]:
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df["Age"] < (Q1 - 1.5 * IQR)) |
              (df["Age"] > (Q3 + 1.5 * IQR))]

print("Total Outliers:", len(outliers))
print(outliers)

Total Outliers: 0
Empty DataFrame
Columns: [ID, Name, Email, Address, age/gender, Souches, Diabetes, Hypertension, Hospital_before, Infection_Freq, AMX/AMP, AMC, CZ, FOX, CTX/CRO, IPM, GEN, AN, Acide nalidixique, ofx, CIP, C, Co-trimoxazole, Furanes, colistine, Collection_Date, Notes, Age, Gender]
Index: []

[0 rows x 29 columns]

In [84]:
df.drop("age/gender",axis=1,inplace=True)

In [85]:
email_index = df.columns.get_loc("Email")

df.insert(email_index + 1, "Age", df.pop("Age"))
df.insert(email_index + 2, "Gender", df.pop("Gender"))

In [86]:
invalid_gender = df[~df["Gender"].isin(["M", "F"])]
print(invalid_gender)
print("Invalid Gender:", len(invalid_gender))

Empty DataFrame
Columns: [ID, Name, Email, Age, Gender, Address, Souches, Diabetes, Hypertension, Hospital_before, Infection_Freq, AMX/AMP, AMC, CZ, FOX, CTX/CRO, IPM, GEN, AN, Acide nalidixique, ofx, CIP, C, Co-trimoxazole, Furanes, colistine, Collection_Date, Notes]
Index: []

[0 rows x 28 columns]
Invalid Gender: 0

In [95]:
df["Souches"].unique()

array(['S290 Escherichia coli', 'S291 Morganella morganii',
       'S292 Proteus mirabilis', ..., 'S10287 Morganella morganii',
       'S10288 Escherichia coli', 'S10289 Escherichia coli'],
      shape=(9299,), dtype=object)

In [96]:
df["Souches"].isnull().sum()

np.int64(640)

In [118]:
df.isnull().sum()

ID                     0
Name                   0
Email                  0
Age                    0
Gender                 0
Address                0
Souches                0
Diabetes               0
Hypertension         630
Hospital_before      637
Infection_Freq       639
AMX/AMP              658
AMC                  632
CZ                   628
FOX                  625
CTX/CRO              624
IPM                  633
GEN                  643
AN                   628
Acide nalidixique    622
ofx                  618
CIP                  633
C                    629
Co-trimoxazole       640
Furanes              637
colistine            636
Collection_Date      669
Notes                112
dtype: int64

In [100]:
df["Souches"].value_counts()

Souches
S6533 Proteus mirabilis      3
S7731 Escherichia coli       3
S4809 Escherichia coli       3
S6976 Escherichia coli       3
S687 E. coli                 3
                            ..
S3742 Enterobacteria spp.    1
S3741 Enterobacteria spp.    1
S3740 Escherichia coli       1
S3739 Escherichia coli       1
S10289 Escherichia coli      1
Name: count, Length: 9296, dtype: int64

In [99]:
df["Souches"]=df["Souches"].replace("?",np.nan)

In [102]:
store=["S290 Escherichia coli",
"S291 Morganella morganii",
"S292 Proteus mirabilis",
"S10287 Morganella morganii",
"S10289 Escherichia coli",
"S10288 Escherichia coli",
]

mask=df["Souches"].isna()
df.loc[mask, "Souches"] = np.random.choice(store, size=mask.sum())

In [116]:
df["Diabetes"].value_counts()

Diabetes
No      8646
True    2064
Name: count, dtype: int64

In [117]:
missing=round((df["Diabetes"].isnull().sum()/len(df))*100,2)
print(f"percentage of missing value:{missing:.2f}%")

percentage of missing value:0.00%

In [112]:
df["Diabetes"]=df["Diabetes"].replace("missing",np.nan)

In [115]:
df["Diabetes"].fillna(df["Diabetes"].mode()[0],inplace=True)

In [119]:
df.head()

,ID,Name,Email,Age,Gender,Address,Souches,Diabetes,Hypertension,Hospital_before,...,AN,Acide nalidixique,ofx,CIP,C,Co-trimoxazole,Furanes,colistine,Collection_Date,Notes
0,S290,Elizabeth Lawrence,elizabeth.lawrence@example.com,37.000000,F,"6350 Robinson Loaf Apt. 447, Paulfurt, RI 30252",S290 Escherichia coli,No,No,No,...,S,S,S,S,R,S,S,S,5 Fev 2025,Patient had fever??
1,S291,Tina Sanders,tina.sanders@example.com,29.000000,F,"78594 Galloway Port Suite 762, South Tanyatown...",S291 Morganella morganii,True,No,No,...,S,S,S,S,S,S,S,S,08/05/2021,تم العلاج
2,S292,Erin Cooke,erin.cooke@example.com,77.000000,F,"76661 Isaiah Manors, North Benjamin, HI 85195",S292 Proteus mirabilis,True,No,No,...,S,S,S,R,R,S,S,S,01/05/2022,NADA
3,S293,Mrs. Sharon Watson,mrs..sharon.watson@example.com,45.601789,F,"1670 Thompson Way Apt. 520, Andrewbury, IL 11534",S292 Proteus mirabilis,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-05,PACIENTO ENFERMO
4,S294,Erika Stewart,erika.stewart@example.com,13.000000,F,"76838 Patrick Green Suite 538, Torresmouth, ME...",S294 Escherichia coli,No,Yes,No,...,R,S,S,S,S,S,S,S,error,NADA

In [126]:
df["Hypertension"].value_counts()

Hypertension
No     8233
Yes    2477
Name: count, dtype: int64

In [123]:
df["Hypertension"]=df["Hypertension"].replace("?",np.nan)

In [125]:
df["Hypertension"].fillna(df["Hypertension"].mode()[0],inplace=True)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_12844\236314252.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Hypertension"].fillna(df["Hypertension"].mode()[0],inplace=True)

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10710 entries, 0 to 10709
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 10710 non-null  object
 1   Name               10710 non-null  object
 2   Email              10710 non-null  object
 3   Age                10710 non-null  int64
 4   Gender             10710 non-null  object
 5   Address            10710 non-null  object
 6   Souches            10710 non-null  object
 7   Diabetes           10710 non-null  object
 8   Hypertension       10710 non-null  object
 9   Hospital_before    10073 non-null  object
 10  Infection_Freq     10071 non-null  object
 11  AMX/AMP            10052 non-null  object
 12  AMC                10078 non-null  object
 13  CZ                 10082 non-null  object
 14  FOX                10085 non-null  object
 15  CTX/CRO            10086 non-null  object
 16  IPM                10077 non-null  object
 17  GEN                10067 non-null  object
 18  AN                 10082 non-null  object
 19  Acide nalidixique  10088 non-null  object
 20  ofx                10092 non-null  object
 21  CIP                10077 non-null  object
 22  C                  10081 non-null  object
 23  Co-trimoxazole     10070 non-null  object
 24  Furanes            10073 non-null  object
 25  colistine          10074 non-null  object
 26  Collection_Date    10041 non-null  object
 27  Notes              10598 non-null  object
dtypes: int64(1), object(27)
memory usage: 2.3+ MB

In [128]:
df["Age"]=df["Age"].astype(int)

In [144]:
df.isnull().sum()

ID                     0
Name                   0
Email                  0
Age                    0
Gender                 0
Address                0
Souches                0
Diabetes               0
Hypertension           0
Hospital_before        0
Infection_Freq       639
AMX/AMP              658
AMC                  632
CZ                   628
FOX                  625
CTX/CRO              624
IPM                  633
GEN                  643
AN                   628
Acide nalidixique    622
ofx                  618
CIP                  633
C                    629
Co-trimoxazole       640
Furanes              637
colistine            636
Collection_Date      669
Notes                112
dtype: int64

In [143]:
df["Hospital_before"].value_counts()

Hospital_before
No     7771
Yes    2939
Name: count, dtype: int64

In [140]:
df["Hospital_before"]=df["Hospital_before"].replace("missing",np.nan)

In [142]:
df["Hospital_before"].fillna(df["Hospital_before"].mode()[0],inplace=True)

C:\Users\uzaif\AppData\Local\Temp\ipykernel_12844\2221617585.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Hospital_before"].fillna(df["Hospital_before"].mode()[0],inplace=True)

In [146]:
df.to_csv("new_Bacteria_dataset.csv",index=False)

In [147]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("new_Bacteria_dataset.csv")
df.head(10)

,ID,Name,Email,Age,Gender,Address,Souches,Diabetes,Hypertension,Hospital_before,...,AN,Acide nalidixique,ofx,CIP,C,Co-trimoxazole,Furanes,colistine,Collection_Date,Notes
0,S290,Elizabeth Lawrence,elizabeth.lawrence@example.com,37,F,"6350 Robinson Loaf Apt. 447, Paulfurt, RI 30252",S290 Escherichia coli,No,No,No,...,S,S,S,S,R,S,S,S,5 Fev 2025,Patient had fever??
1,S291,Tina Sanders,tina.sanders@example.com,29,F,"78594 Galloway Port Suite 762, South Tanyatown...",S291 Morganella morganii,True,No,No,...,S,S,S,S,S,S,S,S,08/05/2021,تم العلاج
2,S292,Erin Cooke,erin.cooke@example.com,77,F,"76661 Isaiah Manors, North Benjamin, HI 85195",S292 Proteus mirabilis,True,No,No,...,S,S,S,R,R,S,S,S,01/05/2022,NADA
3,S293,Mrs. Sharon Watson,mrs..sharon.watson@example.com,45,F,"1670 Thompson Way Apt. 520, Andrewbury, IL 11534",S292 Proteus mirabilis,No,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-05,PACIENTO ENFERMO
4,S294,Erika Stewart,erika.stewart@example.com,13,F,"76838 Patrick Green Suite 538, Torresmouth, ME...",S294 Escherichia coli,No,Yes,No,...,R,S,S,S,S,S,S,S,error,NADA
5,S295,Krystal Riley,krystal.riley@example.com,57,M,"USNS Neal, FPO AA 98816",S295 Escherichia coli,True,No,No,...,R,S,S,S,S,S,S,S,2020-01-05,Patient had fever??
6,S296,Gina Griffin,gina.griffin@example.com,68,F,"389 Ferguson Island, West Jefferymouth, MT 89882",S296 Escherichia coli,No,No,No,...,S,S,S,S,S,S,S,S,2020-12-31,see file
7,S297,Faith Newman,faith.newman@example.com,18,F,"256 Bartlett Fork Suite 334, East Sherri, MI 9...",S297 Citrobacter spp.,No,No,No,...,S,S,S,S,S,R,S,S,05/03/2022,تم العلاج
8,S298,Russell Hicks,russell.hicks@example.com,77,F,"77940 Richard Brook Apt. 748, South Jessica, G...",S298 Enterobacteria spp.,No,No,No,...,S,S,S,S,S,S,S,S,05/01/2025,MALADIE GRAVE
9,S299,Kimberly Rodriguez,kimberly.rodriguez@example.com,36,F,"1979 Kayla Squares Suite 125, West Cynthia, MO...",S299 Proeus mirabilis,No,No,No,...,S,R,S,S,S,S,S,S,08/05/2021,Patient had fever??

In [148]:
df.isnull().sum()

ID                     0
Name                   0
Email                  0
Age                    0
Gender                 0
Address                0
Souches                0
Diabetes               0
Hypertension           0
Hospital_before        0
Infection_Freq       639
AMX/AMP              658
AMC                  632
CZ                   628
FOX                  625
CTX/CRO              624
IPM                  633
GEN                  643
AN                   628
Acide nalidixique    622
ofx                  618
CIP                  633
C                    629
Co-trimoxazole       640
Furanes              637
colistine            636
Collection_Date      669
Notes                112
dtype: int64